# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEjpW-qkCcHgiguiTtWOW8OSzYMLuxB4
"""

pip install streamlit

pip install easyocr

!pip install streamlit pyngrok

!pip install streamlit pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from PIL import Image
# 
# ################
# import cv2
# import easyocr
# import cv2 as cv
# import matplotlib.pyplot as plt
# import numpy as np
# ##################################
# 
# # Title
# st.title(" Text Detection from Image")
# st.write("Upload an image. It will detect and extract all visible text.")
# 
# # Upload image
# uploaded_file = st.file_uploader("Upload an image", type=['png', 'jpg', 'jpeg'])
# 
# if uploaded_file is not None:
#     # Read and convert image
#     image = Image.open(uploaded_file).convert('RGB')
#     img_array = np.array(image)
#     img = cv2.cvtColor(img_array, cv2.COLOR_RGB2BGR)
# ####################################################################################
# 
# 
# #read image
# #image path
# #img_path = r"C:\Users\Abhisek kundu\PycharmProjects\PythonProject\.venv\img.png"
#     # img = cv.imread(img_input)
# 
# 
# #instance text decoder
#     reader = easyocr.Reader(['en'],gpu=False)
# 
# #detect text from image
#     text_ = reader.readtext(img)
# 
# 
# #text printing
#     for i in text_:
#         bbox, text, score = i
#         print(text)
#         cv2.rectangle(img,bbox[0],bbox[2],(0,255,0),5)
#         cv2.putText(img, text, bbox[0], cv2.FONT_HERSHEY_COMPLEX, 1,(0,0,255),2)
# 
# # plt.imshow(cv2.cvtColor(img,    cv2.COLOR_BGR2RGB))
# # plt.show()
#  # Convert BGR to RGB for display
#     img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# 
#     # Output 1: Detected Image
#     st.subheader("Image with Detected Text")
#     st.image(img_rgb, caption="Detected Image")
# 
#     # Output 2: List of All Text
#     st.subheader("Extracted Text:")
#     for i, (bbox, text, score) in enumerate(text_):
#         st.write(f"**{i+1}.** {text} (Confidence: {score:.2f})")
# 
#

# Kill all previous ngrok tunnels
!killall ngrok

from pyngrok import ngrok
ngrok.set_auth_token("2zh8QMx9asGf5LUFlt2KcT0o04x_2sc53aw3e4nvvMuS6trXd")

import time
import os

# Kill previous Streamlit processes
os.system("pkill streamlit")

# Start Streamlit app in background
os.system("streamlit run app.py &")

# Wait to make sure Streamlit starts properly
time.sleep(5)

public_url = ngrok.connect(8501)
print("🔗 Streamlit app is live here:", public_url)